<!--footer-->
<div class="row">
  <div class="col-lg-12 footer">
    <div class="col-lg-3"></div>
    <div class="col-lg-2 padding">Algemene voorwaarden</div>
    <div class="col-lg-3 padding">&#169; Hondsrug College</div>
    <div class="col-lg-4 padding">2017-2018</div>
  </div>
</div>
<!--end footer-->

<?php
  include ("include/close.inc");
?>
<!-- Jquery en Javascripts als laatste -->

<script src="js/jquery-3.2.0.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.js"></script>
