<?php
//  Frank Adema
//  Student Stenden Emmen
//  frank.adema@student.stenden.com
//  leerlingnummer: 277665
//  Jaar: 2017
//  Afstudeeropdracht Exact Anders


//Sessie starten voor gebruiker (leerling, docent, administrator)
session_start();
?>
<!--header-->
<div class="row">
  <div class="col-lg-12 header">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-6">
      <a href="index.php"><img src="images/Hondsrug.png"/>Exact Anders</a>
    </div>
    <div class="col-lg-4 padding">
    </div>
  </div>
</div>

<!--Voor grafieken-->
<script src="js/moments.js"></script>
<!--Chart.js moet na moment.js voor uitlijning-->
<script src="js/Chart.bundle.js"></script>
<!--header-end-->
