<?php
  session_start();
?>
 <!--header-->
<div class="row">
  <div class="col-lg-12 header">
    <div class="col-lg-2"></div>
    <div class="col-lg-6"><a href="index.php"><img src="images/Hondsrug.png"/>Exact Anders</a></div>
    <div class="col-lg-4 padding"></div>
  </div>
</div>

<script src="js/moments.js"></script>
<script src="js/Chart.bundle.js"></script><!--moet na moment.js voor uitlijning-->
<!--header-end-->
